<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.5.2" />
    <ProjectReference Include="..\HemodinksAPI.Api\HemodinksAPI.Api.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>208fab08-8d90-456a-840c-8c15377f7d9f</UserSecretsId>
  </PropertyGroup>

</Project>
