// <auto-generated />
using System;
using HemodinksAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HemodinksAPI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616232745_AddPacienteObservacoes")]
    partial class AddPacienteObservacoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HemodinksAPI.Domain.Models.CbhpmGeral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capitulo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("CustoOperacional")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Grupo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Porte")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Procedimento")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("ValorReferencia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Porte");

                    b.ToTable("CBHPMGeral", (string)null);
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Convenio", b =>
                {
                    b.Property<int>("IdConvenio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConvenio"));

                    b.Property<string>("DescricaoConvenio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdConvenio");

                    b.HasIndex("DescricaoConvenio")
                        .IsUnique();

                    b.ToTable("Convenios", (string)null);

                    b.HasData(
                        new
                        {
                            IdConvenio = 1,
                            DescricaoConvenio = "Amil"
                        },
                        new
                        {
                            IdConvenio = 2,
                            DescricaoConvenio = "Bradesco Saúde"
                        },
                        new
                        {
                            IdConvenio = 3,
                            DescricaoConvenio = "Cemig Saúde"
                        },
                        new
                        {
                            IdConvenio = 4,
                            DescricaoConvenio = "Fusex"
                        },
                        new
                        {
                            IdConvenio = 5,
                            DescricaoConvenio = "Geap"
                        },
                        new
                        {
                            IdConvenio = 6,
                            DescricaoConvenio = "Ipsemg"
                        },
                        new
                        {
                            IdConvenio = 7,
                            DescricaoConvenio = "Particular"
                        },
                        new
                        {
                            IdConvenio = 8,
                            DescricaoConvenio = "Sul América"
                        },
                        new
                        {
                            IdConvenio = 9,
                            DescricaoConvenio = "Unimed Uberlândia - Plano  Unimed Intercâmbio"
                        });
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastReminderSentAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MedicalUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextReminderAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NotifyMedicalProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("NotifyUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ReminderPeriodMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicalUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("NextReminderAt", "IsCompleted");

                    b.HasIndex("Start", "End", "IsCompleted");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.GrupoMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("GruposMedicos", (string)null);
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.GrupoMedicoUsuario", b =>
                {
                    b.Property<int>("GrupoMedicoId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("GrupoMedicoId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GrupoMedicoUsuarios", (string)null);
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Hospitais", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Santa Clara - Mater Dei"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Santa Genoveva - Mater Dei"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "UMC - Complexo Hospitalar"
                        });
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Licenca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataFimLicenca")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFimTrial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioTrial")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeaturesLiberadas")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Licencas", (string)null);
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Observacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataLeitura")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinatarioUserId")
                        .HasColumnType("int");

                    b.Property<string>("Medico")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MedicoAuxiliar1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MedicoAuxiliar1UserId")
                        .HasColumnType("int");

                    b.Property<string>("MedicoAuxiliar2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MedicoAuxiliar2UserId")
                        .HasColumnType("int");

                    b.Property<int?>("MedicoUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ObservacaoPaiId")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ObservacaoPaiId");

                    b.HasIndex("AutorUserId", "DataCadastro");

                    b.HasIndex("PacienteId", "DataCadastro");

                    b.HasIndex("DestinatarioUserId", "DataLeitura", "DataCadastro");

                    b.ToTable("Observacoes", (string)null);
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Opme", b =>
                {
                    b.Property<int>("IdFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFornecedor"));

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdFornecedor");

                    b.HasIndex("Fornecedor")
                        .IsUnique();

                    b.ToTable("OPME", (string)null);

                    b.HasData(
                        new
                        {
                            IdFornecedor = 1,
                            Fornecedor = "Promedom"
                        },
                        new
                        {
                            IdFornecedor = 2,
                            Fornecedor = "AVL"
                        },
                        new
                        {
                            IdFornecedor = 3,
                            Fornecedor = "GE"
                        },
                        new
                        {
                            IdFornecedor = 4,
                            Fornecedor = "Spyner"
                        });
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autorizacao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CbhpmCodigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CbhpmPorte")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Convenio")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ConvenioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Hospital")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Medico")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MedicoAuxiliar1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MedicoAuxiliar1UserId")
                        .HasColumnType("int");

                    b.Property<string>("MedicoAuxiliar2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MedicoAuxiliar2UserId")
                        .HasColumnType("int");

                    b.Property<int?>("MedicoUserId")
                        .HasColumnType("int");

                    b.Property<string>("NomePaciente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OpmeFornecedor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OpmeFornecedorId")
                        .HasColumnType("int");

                    b.Property<string>("Pagamento")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Procedimento")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RepasseGlosa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("StatusPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TratamentoMedico")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CbhpmCodigo");

                    b.HasIndex("ConvenioId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("MedicoAuxiliar1UserId");

                    b.HasIndex("MedicoAuxiliar2UserId");

                    b.HasIndex("MedicoUserId");

                    b.HasIndex("OpmeFornecedorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.PacienteArquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("DataUpload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("PacienteArquivos", (string)null);
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.PacienteProcedimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CbhpmCodigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CbhpmPorte")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<string>("Procedimento")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("ValorReferencia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CbhpmCodigo");

                    b.HasIndex("PacienteId");

                    b.ToTable("PacienteProcedimentos", (string)null);
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "UsedAt", "ExpiresAt");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Perfis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Médicos"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Pacientes"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Controller"
                        });
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Crm")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CrmUf")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PerfilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<bool>("PrecisaTrocarSenha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("[Cpf] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PerfilId");

                    b.HasIndex("Telefone");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.UserArquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("DataUpload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserArquivos", (string)null);
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Event", b =>
                {
                    b.HasOne("HemodinksAPI.Domain.Models.User", "MedicalUser")
                        .WithMany("MedicalEvents")
                        .HasForeignKey("MedicalUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HemodinksAPI.Domain.Models.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.GrupoMedicoUsuario", b =>
                {
                    b.HasOne("HemodinksAPI.Domain.Models.GrupoMedico", "GrupoMedico")
                        .WithMany("Membros")
                        .HasForeignKey("GrupoMedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HemodinksAPI.Domain.Models.User", "User")
                        .WithMany("GruposMedicos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoMedico");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Licenca", b =>
                {
                    b.HasOne("HemodinksAPI.Domain.Models.User", "User")
                        .WithOne("Licenca")
                        .HasForeignKey("HemodinksAPI.Domain.Models.Licenca", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Observacao", b =>
                {
                    b.HasOne("HemodinksAPI.Domain.Models.User", "AutorUser")
                        .WithMany("ObservacoesEnviadas")
                        .HasForeignKey("AutorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HemodinksAPI.Domain.Models.User", "DestinatarioUser")
                        .WithMany("ObservacoesRecebidas")
                        .HasForeignKey("DestinatarioUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HemodinksAPI.Domain.Models.Observacao", "ObservacaoPai")
                        .WithMany()
                        .HasForeignKey("ObservacaoPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HemodinksAPI.Domain.Models.Paciente", "Paciente")
                        .WithMany("Observacoes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutorUser");

                    b.Navigation("DestinatarioUser");

                    b.Navigation("ObservacaoPai");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Paciente", b =>
                {
                    b.HasOne("HemodinksAPI.Domain.Models.Convenio", "ConvenioReferencia")
                        .WithMany("Pacientes")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HemodinksAPI.Domain.Models.Hospital", "HospitalReferencia")
                        .WithMany("Pacientes")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HemodinksAPI.Domain.Models.User", "MedicoAuxiliar1User")
                        .WithMany()
                        .HasForeignKey("MedicoAuxiliar1UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HemodinksAPI.Domain.Models.User", "MedicoAuxiliar2User")
                        .WithMany()
                        .HasForeignKey("MedicoAuxiliar2UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HemodinksAPI.Domain.Models.User", "MedicoUser")
                        .WithMany()
                        .HasForeignKey("MedicoUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HemodinksAPI.Domain.Models.Opme", "OpmeFornecedorReferencia")
                        .WithMany("Pacientes")
                        .HasForeignKey("OpmeFornecedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HemodinksAPI.Domain.Models.User", "User")
                        .WithOne("Paciente")
                        .HasForeignKey("HemodinksAPI.Domain.Models.Paciente", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConvenioReferencia");

                    b.Navigation("HospitalReferencia");

                    b.Navigation("MedicoAuxiliar1User");

                    b.Navigation("MedicoAuxiliar2User");

                    b.Navigation("MedicoUser");

                    b.Navigation("OpmeFornecedorReferencia");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.PacienteArquivo", b =>
                {
                    b.HasOne("HemodinksAPI.Domain.Models.Paciente", "Paciente")
                        .WithMany("Arquivos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.PacienteProcedimento", b =>
                {
                    b.HasOne("HemodinksAPI.Domain.Models.Paciente", "Paciente")
                        .WithMany("Procedimentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.PasswordResetToken", b =>
                {
                    b.HasOne("HemodinksAPI.Domain.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.User", b =>
                {
                    b.HasOne("HemodinksAPI.Domain.Models.Perfil", "Perfil")
                        .WithMany("Users")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.UserArquivo", b =>
                {
                    b.HasOne("HemodinksAPI.Domain.Models.User", "User")
                        .WithMany("Arquivos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Convenio", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.GrupoMedico", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Hospital", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Opme", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Paciente", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("Observacoes");

                    b.Navigation("Procedimentos");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.Perfil", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HemodinksAPI.Domain.Models.User", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("Events");

                    b.Navigation("GruposMedicos");

                    b.Navigation("Licenca");

                    b.Navigation("MedicalEvents");

                    b.Navigation("ObservacoesEnviadas");

                    b.Navigation("ObservacoesRecebidas");

                    b.Navigation("Paciente");

                    b.Navigation("PasswordResetTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
