services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hemodinks-sqlserver-dev
    restart: "no"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SenhaForte@12345"
      MSSQL_PID: "Developer"
      MSSQL_MEMORY_LIMIT_MB: "2048"
    ports:
      - "14330:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
